language: cpp

cache:
  ccache: true

os:
  - linux
dist: bionic

addons:
  apt:
    update: true
    packages:
      - cmake
      - libboost-graph-dev
      - libboost-iostreams-dev
      - libcgal-dev
      - libcgal-qt5-dev
      - libgtest-dev
      - googletest
      - libqt5opengl5-dev
      - libqt5svg5-dev
      - qtbase5-dev

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    - compiler: clang
      env: BUILD_TYPE="Release"
    - compiler: clang
      env: BUILD_TYPE="Debug"
    - compiler: gcc
      env: BUILD_TYPE="Release"
    - compiler: gcc
      env: BUILD_TYPE="Debug"
    - compiler: gcc
      env: BUILD_TYPE="Release" NT_USE_DOUBLE=yes
    - compiler: gcc
      env: BUILD_TYPE="Debug" NT_USE_DOUBLE=yes

script:
 - cmake -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DNT_USE_DOUBLE=${NT_USE_DOUBLE:-no} .
 - make
 - make test
